# TP3 - Numpy library

## I. Matrix creation

In [1]:
import numpy as np

#### Exercise 1 : 1D Matrix

In [2]:
def print_arrays(list_array):
    for array in list_array:
        print('********')
        print(array.shape)
        print(array)


In [3]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
A2 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
B = np.array(range(10))
C = np.linspace(0, 10, 10)
D = np.arange(0, 10, 1)

list_arrays = [A, A2, B, C, D]
print_arrays(list_arrays)

********
(9,)
[1 2 3 4 5 6 7 8 9]
********
(1, 9)
[[1 2 3 4 5 6 7 8 9]]
********
(10,)
[0 1 2 3 4 5 6 7 8 9]
********
(10,)
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
********
(10,)
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# C == D ?
# np.linspace results in float by default
C2 = np.linspace(0, 9, 10, dtype=int)
print(C2)
print(C2.dtype, D.dtype)

# second
np.arange(1, 20)

np.array([3 for i in range(20)])
print(3*np.ones(20, dtype=int))

print(np.arange(30, 8, -3))
# print(np.array([3] * 20))

[0 1 2 3 4 5 6 7 8 9]
int32 int32
[30 27 24 21 18 15 12  9]


In [9]:
# There are 2 ways to use the reshape function:
A2.reshape(3, 3), np.reshape(A, (3, 3))

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

#### Exrcise 2 : 2D Matrix

In [5]:
A = np.eye(3)
B = np.zeros((3, 3))
C = np.ones((3, 3))
D = np.array(range(9)).reshape(3, 3)
E = np.diag([1, 1, 1])
F = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 9]])
G = np.ones((3, 3)) - np.eye(3)
H = np.diag(D)
I = np.diag(np.diag(D))
# np diag will return the diagonal if the input array is 2D
# otherwise if it is 1D it will construct the 2D matrix with input as diagonal

print_arrays([A,B,C,D,E,F,G,H,I])

********
(3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
********
(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
********
(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
********
(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
********
(3, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]]
********
(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 9]]
********
(3, 3)
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
********
(3,)
[0 4 8]
********
(3, 3)
[[0 0 0]
 [0 4 0]
 [0 0 8]]


#### Exercise 3 : Random Creation

In [6]:
A = np.random.randn(3, 3)
B = np.random.randint(0, 9, (3, 3))
C = np.random.rand(3, 3)
print_arrays([A,B,C])


********
(3, 3)
[[ 0.52920913  1.04355997  0.12848517]
 [-1.22515604 -1.18093173 -1.00059203]
 [ 0.42907712 -0.92804421  0.21606417]]
********
(3, 3)
[[0 8 5]
 [6 6 7]
 [6 7 4]]
********
(3, 3)
[[0.77830367 0.32306937 0.37794117]
 [0.81496668 0.81272383 0.91448906]
 [0.52267634 0.35396883 0.97710982]]


In [7]:
A = 10 + 5*np.random.randn(5, 3, 2)
A2 = np.random.normal(10, 5, size=(5,3,2))

B = np.random.rand(3, 1) * 2. - 1.
B2 = np.random.uniform(-1, 1, (3, 1))

C = np.random.randint(0, 100, 100)
print_arrays([A,B,C])

********
(5, 3, 2)
[[[ 5.17870566  6.59155451]
  [-0.73015103 10.06179428]
  [ 9.51534518 17.3577398 ]]

 [[ 8.67461468 13.27179136]
  [ 4.65006218 -1.48811905]
  [10.27592365  5.55053309]]

 [[13.21879671  6.8134102 ]
  [ 9.6881198   8.65911813]
  [15.09914637  8.68174402]]

 [[ 3.03764464 -0.20589008]
  [16.30828515 15.98547123]
  [17.04626169  9.68460151]]

 [[ 7.30137762  7.61119801]
  [ 1.5749255  13.1956314 ]
  [ 7.48202754  7.18744124]]]
********
(3, 1)
[[0.18504648]
 [0.28621076]
 [0.66735012]]
********
(100,)
[29 95 25 25  0 35 82  6 77 71 80 33 56 27 86  1 31 41 23 60 65 28 58 53
 49 67 11 78 60 83 25 74 36 71 66 61 71 99 78 44 47 26 89 75 66 90  5 69
 94 46 14 25 10 43 45 99 20 84 84  4 36 86 91 86 73 37 89 63 44 46 53 85
 81 33 70 55 12 22 30 80  3 24 16 56 33 33 18 57 44 23 82 97 86  2 92  3
 64 62 28 33]


## II. Operations on matrix

#### Exercise 4

In [8]:
L = [1, 2, 3]
A = np.array([1, 2, 3])

print(L + L)  # list concatenation
# print(L + 1)  # Impossible as 1 is not a list
print(3*L)  # 3 times concatenation
# print(L*L)  # Impossible
# print(L**L)  # Impossible
# print(L/L)  # Impossible

print(A + A)  # element-wise aditiion
print(A + 1)  # element-wise addition
print(3*A)  # scalar times matrixs
print(A*A)  # element-wise multiplication
print(A**A)  # element-wise exponentiation
print(A/A)  # element*wise division


[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[2 4 6]
[2 3 4]
[3 6 9]
[1 4 9]
[ 1  4 27]
[1. 1. 1.]


## III. Matrix manipulation
#### Exercise 5 : Indexing

In [20]:
A[0, :]

array([0, 1, 2])

In [17]:
A = np.array(range(9)).reshape(3, 3)

u = A[0, :]
v = A[:, 1]
w = A[[0, 2], [0, 2]]

x = A[[0, 1, 2], [2, 1, 0]]
x2 = np.diag(A[:,::-1])

C = A[:2, :]
C2 = A[[0,1], :]

D = A[:, [0, 2]]

E = A[1::-1, [0, 2]]

F = A[::-1, ::-1]

list_arrays = [A, u, v, w, x, C, D, E, F]
print_arrays(list_arrays)

********
(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
********
(3,)
[0 1 2]
********
(3,)
[1 4 7]
********
(2,)
[0 8]
********
(3,)
[2 4 6]
********
(2, 3)
[[0 1 2]
 [3 4 5]]
********
(3, 2)
[[0 2]
 [3 5]
 [6 8]]
********
(2, 2)
[[3 5]
 [0 2]]
********
(3, 3)
[[8 7 6]
 [5 4 3]
 [2 1 0]]


#### Exercise 6 :  Multiplication


In [29]:
A = np.array([[7, 0], [3, 2], [3, -4]])
B = np.array([[1, 2], [0, -3]])
C = np.array([[1], [2]])
D = np.array([[5, -3]])

print(A.T)
np.dot(A, B)       # (3, 2) * (2, 2) -> (3, 2)
print(np.dot(A, B))
# np.dot(A.T, B)  # Impossible
# np.dot(B, A)  # Impossible
np.dot(B, A.T) # (2, 2) * (2, 3) -> (2, 3)
# np.dot(C, A)  # Impossible (2, 1) * (3, 2)
np.dot(A, C) # (3, 2) * (2, 1) -> (3, 1)
np.dot(D, C) # (1, 2) * (2, 1) -> (1, 1)
np.dot(D, B).dot(C) # (1, 2) * (2, 2) * (2, 1)
np.dot(A.T, A) # (2, 3) * (3, 2) -> (2, 2)
np.dot(A, A.T) # (3, 2) * (2, 3) -> (3, 3)

[[ 7  3  3]
 [ 0  2 -4]]
[[ 7 14]
 [ 3  0]
 [ 3 18]]


array([[49, 21, 21],
       [21, 13,  1],
       [21,  1, 25]])

#### Exercise 7 : Boolean indexing

In [40]:
A = np.random.randint(0, 9, (3, 3))

list_index = []
for i in range(3):
    for j in range(3):
        if A[i,j] > 5:
            print('{} : {}'.format(i,j))
            list_index.append((i, j))
print("\nA = \n", A)
print("\nElements < 5:", list_index)

0 : 0
1 : 0
1 : 1
1 : 2
2 : 0

A = 
 [[8 2 1]
 [7 7 6]
 [7 2 3]]

Elements < 5: [(0, 0), (1, 0), (1, 1), (1, 2), (2, 0)]


In [34]:
print("A = \n", A, '\n\nA > 5: \n', A > 5)

A = 
 [[0 1 6]
 [1 0 7]
 [7 6 7]] 

A > 5: 
 [[False False  True]
 [False False  True]
 [ True  True  True]]


In [41]:
A[2, 2] = -15
print(A)

[[  8   2   1]
 [  7   7   6]
 [  7   2 -15]]


In [36]:
comp_A = A>5
comp_A.dtype

dtype('bool')

In [42]:
"The previous code is not very good looking and quite long, let's do it now faster with vectorization allowed by numpy"

print(A > 5, (A > 5).shape, type(A > 5))

print(A[A > 5], A[A > 5].shape, type(A[A > 5]))
print(np.where(A > 5), type(np.where(A > 5)))

x, y = np.where(A > 5)
# Yields the indices as a tuple where the condition is verified (similar to np.nonzero())
print(x, y)
A[np.where(A > 5)]
print(A[np.where(A > 5)])

B = A
print(B)
B[B < 2] = 0
B[B > 7] = 0
# or B[(B < 2) & (B > 7)] = 0
print(B)

[[ True False False]
 [ True  True  True]
 [ True False False]] (3, 3) <class 'numpy.ndarray'>
[8 7 7 6 7] (5,) <class 'numpy.ndarray'>
(array([0, 1, 1, 1, 2]), array([0, 0, 1, 2, 0])) <class 'tuple'>
[0 1 1 1 2] [0 0 1 2 0]
[8 7 7 6 7]
[[  8   2   1]
 [  7   7   6]
 [  7   2 -15]]
[[0 2 0]
 [7 7 6]
 [7 2 0]]


## IV. Functions
#### Exercise 8 : Basic functions

In [14]:
A = np.array(range(9)).reshape(3, 3)

print(np.log(A))
print(np.sin(A))
print(np.cos(A))
print(np.sqrt(A))
print(np.exp(A))  

[[      -inf 0.         0.69314718]
 [1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154]]
[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825]]
[[ 1.          0.54030231 -0.41614684]
 [-0.9899925  -0.65364362  0.28366219]
 [ 0.96017029  0.75390225 -0.14550003]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]]


c:\users\sonia.martinot\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


#### Exercise 9 : Statistics

In [15]:
A = np.random.randint(0, 20, (2, 3, 2, 3))

print(np.max(A))
print(np.max(A, axis=0).shape)
print(np.max(A, axis=3).shape)
print(np.max(A, axis=(2, 3)).shape)

19
(3, 2, 3)
(2, 3, 2)
(2, 3)


#### Exercise 10 : Concatenation functions

In [16]:
A = np.array(range(9)).reshape(3, 3)
B = np.concatenate((A, A, A), axis=0)
C = np.concatenate((A, A, A), axis=1)
D = np.stack((A, A, A), axis=0)
print('*** B ***')
print(B)
print(B.shape)
print('*** C ***')
print(C)
print(C.shape)

print('*** D ***')
print(D)
print(D.shape)

*** B ***
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
(9, 3)
*** C ***
[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [6 7 8 6 7 8 6 7 8]]
(3, 9)
*** D ***
[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]]
(3, 3, 3)
